namespace CoreBot.Core.Messages;

/// <summary>
/// Response generated by the AI agent
/// </summary>
public record AgentResponse(
    string MessageId,
    DateTime Timestamp,
    string Platform,
    string UserId,
    string Content,
    List<ToolCall>? ToolCalls
) : IMessage;
